# Generated by Django 3.1.6 on 2021-02-06 12:41

import diagnosis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20210205_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTypeCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueryMediatorToggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system_assigned', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=False)),
                ('requested_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('voice', models.FileField(blank=True, max_length=1000, upload_to=diagnosis.models.get_user_query_voice_upload_destination)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cropcv')),
                ('query_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.experttypecv')),
            ],
        ),
        migrations.CreateModel(
            name='UserQueryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQueryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=diagnosis.models.get_user_query_image_upload_destination)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('user_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.userquery')),
            ],
        ),
        migrations.AddField(
            model_name='userquery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.userquerystatus'),
        ),
        migrations.AddField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(blank=True, max_length=1000, null=True, upload_to=diagnosis.models.get_recommendation_voice_upload_destination)),
                ('notes', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by_expert_user', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_reviewed', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.recommendationstatus')),
                ('user_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.userquery')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=diagnosis.models.get_recommendation_image_upload_destination)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.recommendationlog')),
            ],
        ),
        migrations.CreateModel(
            name='QueryExpertAssignMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_assigned_by_user', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_assigned_to_user', to=settings.AUTH_USER_MODEL)),
                ('user_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.userquery')),
            ],
        ),
        migrations.CreateModel(
            name='QueryCategoryExpertUserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('expert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.experttypecv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
