# Generated by Django 3.1.6 on 2021-02-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210205_1408'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cropcv'),
        ),
    ]
