# Generated by Django 3.1.6 on 2021-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_userquery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
