# Generated by Django 3.1.6 on 2021-08-18 13:08

import diagnosis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosis', '0005_recommendationlog_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('file', models.FileField(upload_to=diagnosis.models.get_publish_file_upload_destination)),
                ('circular_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
