# Generated by Django 3.1.6 on 2021-08-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_circularlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circularlog',
            old_name='discription',
            new_name='description',
        ),
    ]
