# Generated by Django 3.1.6 on 2021-08-19 10:42

import diagnosis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_auto_20210818_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=diagnosis.models.get_publish_file_upload_destination),
        ),
    ]
