# Generated by Django 3.1.6 on 2021-08-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_auto_20210819_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
