# Generated by Django 3.1.6 on 2021-08-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_auto_20210825_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularlog',
            name='circular_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.circularcategory'),
            preserve_default=False,
        ),
    ]
