# Generated by Django 3.1.6 on 2021-12-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20211206_1234'),
        ('diagnosis', '0012_auto_20210825_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='crop',
        ),
        migrations.AddField(
            model_name='userquery',
            name='clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clone'),
        ),
    ]
