# Generated by Django 3.1.6 on 2021-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
