# Generated by Django 3.1.6 on 2022-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_base64_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
