# Generated by Django 3.1.6 on 2022-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
