# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPacketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('recieved_date', models.DateTimeField(blank=True, null=True)),
                ('dispatched_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispatched_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_dispatched_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InputBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('date_of_manufacturing', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('date_of_receipt', models.DateField()),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_batch_created_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputBatchLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_prefix', models.CharField(max_length=10)),
                ('label_suffix', models.CharField(max_length=10)),
                ('label_range_start', models.PositiveIntegerField()),
                ('label_range_end', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InputItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_combo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_item_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_item_modified_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItem')),
            ],
        ),
        migrations.CreateModel(
            name='InputItemInputBatchMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputBatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_item_input_batch_map_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItem')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_item_input_batch_modified_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputItemInputBatchStorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_section', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_receipt', models.DateField()),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_storage_location_map_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('item_batch_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchMap')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_storage_location_batch_modified_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputItemInputBatchStorageLocationPacketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('recieved_date', models.DateTimeField(blank=True, null=True)),
                ('dispatched_date', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_batch_packet_labeled_dispatched_by_instance', to=settings.AUTH_USER_MODEL)),
                ('item_batch_storage_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchStorageLocation')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_batch_packet_labeled_recieved_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_part_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItem')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_part_modified_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputStockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_created_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('factor_to_base_si_unit', models.PositiveIntegerField()),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.BaseUnit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpOrDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='direction_to_base_si_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.UpOrDown'),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.UnitType'),
        ),
        migrations.AddField(
            model_name='storage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.StorageType'),
        ),
        migrations.AddField(
            model_name='inputpart',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='inputiteminputbatchstoragelocationpacketlabel',
            name='stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStockStatus'),
        ),
        migrations.AddField(
            model_name='inputiteminputbatchstoragelocation',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Storage'),
        ),
        migrations.AddField(
            model_name='inputiteminputbatchstoragelocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='inputiteminputbatchmap',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='inputitemgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputType'),
        ),
        migrations.AddField(
            model_name='inputitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputType'),
        ),
        migrations.AddField(
            model_name='inputitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='inputbatchlabel',
            name='input_item_input_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchMap'),
        ),
        migrations.AddField(
            model_name='inputbatch',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputType'),
        ),
        migrations.AddField(
            model_name='inputbatch',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_batch_modified_by_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputbatch',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='baseunit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.UnitType'),
        ),
        migrations.AddField(
            model_name='agentpacketlabel',
            name='stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStockStatus'),
        ),
    ]
