# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_auto_20200319_1642'),
        ('inputdistri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputitem',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
    ]
