# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0002_inputitem_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputItemInputBatchAgentInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField()),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputitem_inputbatch_agent_inventory_created', to=settings.AUTH_USER_MODEL)),
                ('item_batch_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchMap')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputitem_inputbatch_agent_inventory_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit')),
            ],
        ),
    ]
