# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0003_inputiteminputbatchagentinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentpacketlabel',
            name='agent',
        ),
        migrations.AlterField(
            model_name='agentpacketlabel',
            name='recieved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputiteminputbatchstoragelocationpacketlabel',
            name='recieved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
