# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0004_auto_20200320_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpacketlabel',
            name='inputitem_inputbatch_agent_inventory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchAgentInventory'),
            preserve_default=False,
        ),
    ]
