# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0005_agentpacketlabel_inputitem_inputbatch_agent_inventory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputItemReturnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('date_of_return', models.DateField()),
                ('label_range_from', models.CharField(max_length=15)),
                ('label_range_to', models.CharField(max_length=15)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('item_batch_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputItemInputBatchMap')),
                ('return_data_stored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_data_stored_by', to=settings.AUTH_USER_MODEL)),
                ('returned_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit')),
            ],
        ),
    ]
