# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0008_auto_20200531_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='procurement_transaport_incharge_kyc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ProcurementTransportInchargeKyc'),
        ),
    ]
