# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0009_auto_20200531_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='vehicle_driver_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurement',
            name='vehicle_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
