# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0011_harvestlevel_yeildprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='empty_vehicle_weight_data_inputed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='loaded_vehicle_weight_data_inputed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='moisture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procurement',
            name='ticket_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
