# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0013_auto_20200617_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='str_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
