# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0014_procurement_str_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='str_weight_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='str_weight_unit', to='inputdistri.Unit'),
            preserve_default=False,
        ),
    ]
