# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0015_procurement_str_weight_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='business',
        ),
    ]
