# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0027_auto_20200614_0641'),
        ('inputdistri', '0015_procurement_str_weight_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProcurementPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ProcurementProduce')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
            ],
        ),
    ]
