# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0016_remove_harvest_business'),
        ('inputdistri', '0016_auto_20200621_0640'),
    ]

    operations = [
    ]
