# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0027_auto_20200614_0641'),
        ('inputdistri', '0017_merge_20200621_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduceProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProduceProcurementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticket_number', models.CharField(max_length=50)),
                ('str_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ProcurementProduce')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='ticket_number',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerproduceprocurement',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.FarmerProduceProcurementGroup'),
        ),
        migrations.AddField(
            model_name='farmerproduceprocurement',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer'),
        ),
        migrations.AddField(
            model_name='farmerproduceprocurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
    ]
