# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0018_auto_20200624_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduceprocurement',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='farmerproduceprocurement',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerproduceprocurement',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='farmerproduceprocurementgroup',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='farmerproduceprocurementgroup',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='farmerproduceprocurementgroup',
            name='unit',
        ),
        migrations.DeleteModel(
            name='FarmerProduceProcurement',
        ),
        migrations.DeleteModel(
            name='FarmerProduceProcurementGroup',
        ),
    ]
