# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0020_auto_20200624_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='reason_for_weight_loss',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
