# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0021_procurement_reason_for_weight_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementgroup',
            name='agent_price_deduction',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
