# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0022_procurementgroup_agent_price_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
