# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0025_auto_20200727_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
