# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0027_auto_20200729_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='ticket_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
