# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0028_auto_20200806_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='have_other_agent_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
