# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0031_auto_20210223_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputPacketInventoryCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
                ('code_prefix', models.CharField(max_length=5)),
            ],
        ),
    ]
