# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0033_auto_20210224_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboIssueRequestCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
                ('input_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo')),
            ],
        ),
        migrations.RenameField(
            model_name='areacv',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='areacv',
            name='quantity_in_acre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comboissuerequestagentmap',
            name='max_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.MaxStatus'),
            preserve_default=False,
        ),
    ]
