# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0036_auto_20210224_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboissuerequest',
            name='quantity_for_area',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
