# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0037_auto_20210224_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField()),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputitem_inputbatch_agent_inventory_created', to=settings.AUTH_USER_MODEL)),
                ('input_store_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStoreInventory')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputitem_inputbatch_agent_inventory_modified', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInventoryPacketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('recieved_date', models.DateTimeField()),
                ('dispatched_date', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory')),
                ('dispatched_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_dispatched_to_user', to=settings.AUTH_USER_MODEL)),
                ('stock_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStockStatus')),
            ],
        ),
    ]
