# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0038_agentinventory_agentinventorypacketlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIssueLabelAgentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='agentinventory',
            name='input_store_inventory',
        ),
        migrations.AddField(
            model_name='storeissuelabelagentmap',
            name='agent_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory'),
        ),
        migrations.AddField(
            model_name='storeissuelabelagentmap',
            name='combo_issue_request_agent_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequestAgentMap'),
        ),
        migrations.AddField(
            model_name='storeissuelabelagentmap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_label_agent_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeissuelabelagentmap',
            name='input_store_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStoreInventory'),
        ),
        migrations.AddField(
            model_name='storeissuelabelagentmap',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_label_agent_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
