# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0040_auto_20210226_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputstoreinventory',
            name='label_range_end',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputstoreinventory',
            name='label_range_start',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
