# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0041_auto_20210226_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboIssueRegisterAgentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_numbers', models.PositiveIntegerField(default=0)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user_id_for_request_register', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_user_id_for_request_register', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
