# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0042_comboissueregisteragentmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboissueregisteragentmap',
            name='input_combo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo'),
            preserve_default=False,
        ),
    ]
