# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0043_comboissueregisteragentmap_input_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInventoryCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agentinventorypacketlabel',
            name='agent_inventory',
        ),
        migrations.RemoveField(
            model_name='agentinventorypacketlabel',
            name='dispatched_to',
        ),
        migrations.RemoveField(
            model_name='agentinventorypacketlabel',
            name='stock_status',
        ),
        migrations.AddField(
            model_name='agentinventory',
            name='label_range_from',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentinventory',
            name='label_range_to',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AgentInventoryPacketLabel',
        ),
    ]
