# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0045_auto_20210301_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInventoryStoreLabelRangeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_range_from', models.CharField(max_length=15)),
                ('label_range_to', models.CharField(blank=True, max_length=15, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentinventory',
            name='combo_issue_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequest'),
        ),
        migrations.AddField(
            model_name='agentinventorystorelabelrangemap',
            name='agent_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory'),
        ),
        migrations.AddField(
            model_name='agentinventorystorelabelrangemap',
            name='input_store_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStoreInventory'),
        ),
    ]
