# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0046_auto_20210302_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinventory',
            name='label_range_from',
        ),
        migrations.RemoveField(
            model_name='agentinventory',
            name='label_range_to',
        ),
    ]
