# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0035_auto_20210213_0649'),
        ('inputdistri', '0047_auto_20210302_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSubStoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_section', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_receipt', models.DateField()),
                ('quantity_at_receipt', models.PositiveIntegerField()),
                ('quantity_now', models.PositiveIntegerField()),
                ('quantity_now_time', models.DateTimeField()),
                ('label_range_start', models.PositiveIntegerField()),
                ('label_range_end', models.PositiveIntegerField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_storage_location_map_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('input_store_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStoreInventory')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_storage_location_batch_modified_by_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputSubStoreInventoryPacketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('received_date', models.DateTimeField()),
                ('dispatched_date', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_store_batch_packet_labeled_dispatched_by_instance', to=settings.AUTH_USER_MODEL)),
                ('input_sub_store_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputSubStoreInventory')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_store_batch_packet_labeled_recieved_by_instance', to=settings.AUTH_USER_MODEL)),
                ('stock_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputStockStatus')),
            ],
        ),
        migrations.CreateModel(
            name='SubStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_storage_created_by_instance', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.StorageType')),
            ],
        ),
        migrations.CreateModel(
            name='SubStoreIssueLabelAgentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user', to=settings.AUTH_USER_MODEL)),
                ('agent_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory')),
                ('combo_issue_request_agent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequestAgentMap')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_label_agent_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_label_agent_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubStoreRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField()),
                ('responsed_at', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
                ('responsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubStoreRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='agent_inventory',
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='combo_issue_request_agent_map',
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='input_store_inventory',
        ),
        migrations.RemoveField(
            model_name='storeissuelabelagentmap',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='agentinventorystorelabelrangemap',
            name='input_store_inventory',
        ),
        migrations.DeleteModel(
            name='StoreIssueLabelAgentMap',
        ),
        migrations.AddField(
            model_name='substorerequestlog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.SubStoreRequestStatus'),
        ),
        migrations.AddField(
            model_name='substorerequestlog',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.SubStorage'),
        ),
        migrations.AddField(
            model_name='substorerequestlog',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
        migrations.AddField(
            model_name='inputsubstoreinventory',
            name='sub_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.SubStorage'),
        ),
        migrations.AddField(
            model_name='inputsubstoreinventory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.Unit'),
        ),
    ]
