# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-03 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0047_auto_20210302_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboissuerequest',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comboissuerequest',
            name='dispatch_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_status', to='inputdistri.IssueRequestStatus'),
        ),
        migrations.AddField(
            model_name='comboissuerequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
