# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0049_auto_20210305_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substorerequestlog',
            name='responsed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
