# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0052_substorerequestlog_input_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStoreRequestCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='substorerequestlog',
            name='input_sub_store_inventory',
            field=models.ManyToManyField(to='inputdistri.InputSubStoreInventory'),
        ),
        migrations.AddField(
            model_name='substorerequestlog',
            name='request_code',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
