# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0053_auto_20210306_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='substorerequestcodebank',
            name='code_prefix',
            field=models.CharField(default='Req', max_length=10),
            preserve_default=False,
        ),
    ]
