# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0054_substorerequestcodebank_code_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsubstoreinventory',
            name='label_range_end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inputsubstoreinventory',
            name='label_range_start',
            field=models.CharField(max_length=50),
        ),
    ]
