# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0056_substorerequestlog_declined_reason'),
        ('inputdistri', '0048_auto_20210303_0606'),
    ]

    operations = [
    ]
