# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inputdistri.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0035_auto_20210213_0649'),
        ('inputdistri', '0057_merge_20210306_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReceiptBillNumberCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_bill_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComboIssueAgentInventoryReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=inputdistri.models.get_path_for_agent_receipt)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentinventory',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comboissuerequest',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputgoods',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputpacketinventory',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputstoreinventory',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputsubstoreinventory',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comboissueagentinventoryreceipt',
            name='agent_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory'),
        ),
        migrations.AddField(
            model_name='comboissueagentinventoryreceipt',
            name='combo_issue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequest'),
        ),
    ]
