# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0058_auto_20210306_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboissueagentinventoryreceipt',
            name='agent_inventory',
        ),
        migrations.AddField(
            model_name='comboissueagentinventoryreceipt',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
