# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0059_auto_20210306_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboIssueDeleteAgentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_raised_date', models.DateTimeField()),
                ('quantity_in_numbers', models.PositiveIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_agent_user_id', to=settings.AUTH_USER_MODEL)),
                ('combo_issue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequest')),
                ('removed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
