# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import inputdistri.models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0061_auto_20210417_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboissuerequestagentmap',
            name='issue_notice',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=inputdistri.models.get_path_for_agent_issue_notice),
        ),
    ]
