# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0063_agentissuenoticenumbercodebank'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboissuerequestagentmap',
            name='shop_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
