# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-08 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0044_farmerclusterseasonmap_seasonal_farmer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0064_comboissuerequestagentmap_shop_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComboReturnRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=50)),
                ('request_raised_date', models.DateTimeField()),
                ('max_status_date', models.DateTimeField()),
                ('senior_supervisor_remarks', models.TextField(blank=True, null=True)),
                ('assitant_manager_remarks', models.TextField(blank=True, null=True)),
                ('assitant_manager_status_date', models.DateTimeField(blank=True, null=True)),
                ('agri_officer_remarks', models.TextField(blank=True, null=True)),
                ('agri_officer_status_date', models.DateTimeField(blank=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requested_agent', to=settings.AUTH_USER_MODEL)),
                ('agri_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request_agri_officer_user_id', to=settings.AUTH_USER_MODEL)),
                ('agri_officer_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request_agri_officer_status', to='inputdistri.IssueRequestStatus')),
                ('assitant_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request_asst_manager_user_id', to=settings.AUTH_USER_MODEL)),
                ('assitant_manager_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request_assitant_manager_status', to='inputdistri.IssueRequestStatus')),
                ('input_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo')),
                ('max_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.MaxStatus')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
                ('senior_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request_senior_supervisor_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComboReturnRequestLabelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dispatchable', models.BooleanField()),
                ('combo_remarks', models.TextField(blank=True, null=True)),
                ('date_of_return', models.DateField()),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('combo_return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboReturnRequest')),
                ('return_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.SubStoreIssueLabelAgentMap')),
                ('return_sub_store_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputSubStoreInventory')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnableComboItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
            ],
        ),
        migrations.AddField(
            model_name='substoreissuelabelagentmap',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_status', to='inputdistri.AvailabilityStatus'),
        ),
    ]
