# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-09 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0065_auto_20210508_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboReturnRequestCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
                ('input_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo')),
            ],
        ),
    ]
