# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-11 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0066_comboreturnrequestcodebank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxStatusForReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
    ]
