# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0067_maxstatusforreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboreturnrequest',
            name='max_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.MaxStatusForReturn'),
        ),
    ]
