# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0044_farmerclusterseasonmap_seasonal_farmer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0068_auto_20210511_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFarmerDistributionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFarmerDistributionSowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_unit', models.PositiveIntegerField()),
                ('acre', models.PositiveIntegerField()),
                ('dispatched_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('input_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.InputCombo')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing')),
            ],
        ),
        migrations.AddField(
            model_name='agentfarmerdistributionmap',
            name='agent_farmer_distribution_sowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentFarmerDistributionSowing'),
        ),
        migrations.AddField(
            model_name='agentfarmerdistributionmap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentfarmerdistributionmap',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.SubStoreIssueLabelAgentMap'),
        ),
        migrations.AddField(
            model_name='agentfarmerdistributionmap',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
