# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0070_auto_20210602_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPriceChangeRequestCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AgentPriceChangeRequest',
            new_name='AgentDistributionPriceChangeRequest',
        ),
        migrations.RenameModel(
            old_name='AgentPriceChangeRequestStatus',
            new_name='DistributionAgentPriceChangeRequestStatus',
        ),
    ]
