# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0045_farmerbankdetails_remarks'),
        ('inputdistri', '0071_auto_20210602_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdistributionprice',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
        ),
    ]
