# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0075_tempprocurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempprocurement',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
    ]
