# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0076_auto_20210614_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDistributionTransactionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentInventory')),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentTransactionLog')),
            ],
        ),
        migrations.CreateModel(
            name='InputReturnTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboReturnRequest')),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentTransactionLog')),
            ],
        ),
    ]
