# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0079_deleteprocurementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteTempProcurementTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, unique=True)),
                ('id_company', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('vehicle_driver_name', models.CharField(max_length=50)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_time', models.DateTimeField()),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_time', models.DateTimeField()),
                ('net_wt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bag_number', models.PositiveIntegerField()),
                ('bag_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_operator', models.CharField(max_length=30)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_operator', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
