# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0080_deletetempprocurementtrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDistributionOtherStoreTransactionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_issue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.ComboIssueRequest')),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AgentTransactionLog')),
            ],
        ),
    ]
