# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0082_agentmergeloadenable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmergeloadenable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enabled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
