# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0084_auto_20210915_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='travelled_kilometre',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
