# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0085_allowance_travelled_kilometre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='travelled_kilometre',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
