# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-28 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0086_auto_20210924_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='travelled_kilometre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travelallowancedetilas',
            name='from_kilometre',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelallowancedetilas',
            name='to_kilometre',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
