# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0087_auto_20210928_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypewiseallowancecost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
