# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0088_auto_20210928_0504'),
    ]

    operations = [
       
    ]
