# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0089_auto_20220216_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
