# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-25 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0090_allowance_description'),
    ]

    operations = [
    
    ]
