# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-26 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0091_auto_20220225_0940'),
        ('inputdistri', '0089_auto_20220105_0519'),
    ]

    operations = [
    ]
