# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0092_merge_20220226_0727'),
    ]

    operations = [
    ]
