# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0094_auto_20220507_0724'),
    ]

    operations = [
        
    ]
