# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0096_auto_20220512_1500'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='allowance',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='travelallowancedetilas',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='allowance',
            name='max_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.MaxStatus'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='max_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertypewiseallowancecost',
            name='max_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.MaxStatus'),
        ),
        migrations.AlterField(
            model_name='usertypewiseallowancecost',
            name='max_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
