# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-18 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputdistri', '0097_auto_20220513_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='agri_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agri_offcier_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='agri_officer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agri_officer_status_allowance', to='inputdistri.IssueRequestStatus'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='agri_officer_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='assitant_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_manager_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='assitant_manager_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assitant_manager_status_allowance', to='inputdistri.IssueRequestStatus'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='assitant_manager_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='allowance',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='allowance',
            name='gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='gm_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_status_allowance', to='inputdistri.IssueRequestStatus'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='gm_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='senior_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_supervisor_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='senior_supervisor_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_supervisor_status_allowance', to='inputdistri.IssueRequestStatus'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='senior_supervisor_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='travelallowancedetilas',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='allowance',
            name='allowance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputdistri.AllowanceType'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
