# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0112_auto_20220809_1349'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='allowance',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='travelallowancedetilas',
        #     name='date',
        #     field=models.DateField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='procurement',
            name='utr_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
