# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inputdistri', '0113_auto_20220810_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelallowancedetilas',
            name='date',
            field=models.DateField(default='null'),
            preserve_default=False,
        ),
    ]
