# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('micr_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
