# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
