# Generated by Django 3.1.6 on 2021-02-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210205_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
                ('prefix_code', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix_code', models.CharField(blank=True, max_length=10, null=True)),
                ('last_count', models.IntegerField(default=0)),
                ('last_count_length', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district')),
            ],
            options={
                'unique_together': {('district', 'purpose')},
            },
        ),
    ]
