# Generated by Django 3.1.6 on 2021-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210218_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
