# Generated by Django 3.1.6 on 2021-02-25 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210218_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
