# Generated by Django 3.1.6 on 2021-03-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_languageterm_languagetransformterm'),
        ('main', '0008_otp_expiry_time'),
    ]

    operations = [
    ]
