# Generated by Django 3.1.6 on 2021-03-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20210317_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='revenue_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.revenuevillage'),
        ),
    ]
