# Generated by Django 3.1.6 on 2021-03-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210323_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.castecv'),
        ),
    ]
