# Generated by Django 3.1.6 on 2021-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210323_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='area_in_hectare',
            new_name='area_in_acre',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='area_in_hectare',
            new_name='area_in_acre',
        ),
    ]
