# Generated by Django 3.1.6 on 2021-03-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210324_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farm_holding_size_in_hectare',
            new_name='farm_holding_size_in_acre',
        ),
    ]
