# Generated by Django 3.1.6 on 2021-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_microservice_microserviceauthentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='microserviceauthentication',
            name='base_url',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
