# Generated by Django 3.1.6 on 2021-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_microserviceauthentication_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microserviceauthentication',
            name='base_url',
            field=models.CharField(max_length=50),
        ),
    ]
