# Generated by Django 3.1.6 on 2021-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210405_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ms_farmer_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
