# Generated by Django 3.1.7 on 2021-04-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210410_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('route_url', models.CharField(blank=True, max_length=70, null=True)),
                ('icon_path', models.CharField(blank=True, max_length=70, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeTilesMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_ordinal', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tile')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
            ],
        ),
    ]
