# Generated by Django 3.1.7 on 2021-04-22 11:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tile_usertypetilesmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='tile',
            name='image',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_tile_image_path),
        ),
    ]
