# Generated by Django 3.1.7 on 2021-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210422_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='image',
        ),
        migrations.AddField(
            model_name='tile',
            name='icon_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertypetilesmap',
            name='is_icon_available',
            field=models.BooleanField(default=True),
        ),
    ]
