# Generated by Django 3.1.7 on 2021-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210423_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypetilesmap',
            name='column_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
