# Generated by Django 3.1.7 on 2021-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_usertypetilesmap_column_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypetilesmap',
            name='icon_class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertypetilesmap',
            name='title_class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
