# Generated by Django 3.1.6 on 2021-05-20 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210423_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryofficecropmap',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nurseryofficecropmap',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseryofficecropmap',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
