# Generated by Django 3.1.6 on 2021-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210520_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='tab_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
