# Generated by Django 3.1.6 on 2021-08-12 11:37

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForestOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head_office', models.BooleanField(default=False)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('image', models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_forest_office_image)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district')),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forest')),
                ('revenue_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.revenuevillage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state')),
            ],
        ),
        migrations.CreateModel(
            name='ForestOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contact_person', models.BooleanField(default=False)),
                ('forest_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forestoffice')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ForestOfficeCropMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cropcv')),
                ('forest_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forestoffice')),
                ('procurement_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wooduse')),
            ],
        ),
    ]
