# Generated by Django 3.1.6 on 2021-08-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_forest_forestoffice_forestofficecropmap_forestofficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuheader')),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuheader')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPagePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_header_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuheaderpage')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
            ],
        ),
    ]
