# Generated by Django 3.1.6 on 2021-09-07 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_farmerbulkuploadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestofficecropmap',
            name='crop_cv',
        ),
        migrations.RemoveField(
            model_name='forestofficecropmap',
            name='procurement_purpose',
        ),
        migrations.AddField(
            model_name='forestofficecropmap',
            name='clone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.clone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestofficecropmap',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forestofficecropmap',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestofficecropmap',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
