# Generated by Django 3.1.6 on 2021-12-04 16:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210907_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypetilesmap',
            name='display_image',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_display_image_destination),
        ),
    ]
