# Generated by Django 3.1.6 on 2021-12-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0042_auto_20211206_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyorOfficialMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('industry_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.industryoffice')),
                ('institute_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.instituteoffice')),
                ('nursery_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nurseryoffice')),
                ('superior_user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
