# Generated by Django 3.1.6 on 2021-12-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0043_surveyorofficialmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryOfficeCropPriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursery_office_price_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursery_office_price_modified_by', to=settings.AUTH_USER_MODEL)),
                ('nursery_office_crop_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nurseryofficecropmap')),
            ],
        ),
    ]
