# Generated by Django 3.1.6 on 2021-12-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_nurseryofficecroppricelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseryofficecroppricelog',
            old_name='nursery_office_crop_map',
            new_name='nursery_office_crop_price_log',
        ),
    ]
