# Generated by Django 3.1.6 on 2022-01-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_notificationcv_background'),
        ('main', '0049_journal_category'),
    ]

    operations = [
    ]
