# Generated by Django 3.1.6 on 2022-01-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20220108_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsertypeWiseUserManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_url', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('language_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
            ],
        ),
    ]
