# Generated by Django 3.1.6 on 2022-01-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_usertypewiseusermanual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertypewiseusermanual',
            old_name='manual_url',
            new_name='english_manual_url',
        ),
        migrations.RemoveField(
            model_name='usertypewiseusermanual',
            name='language_preference',
        ),
        migrations.AddField(
            model_name='usertypewiseusermanual',
            name='display_ordinal',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertypewiseusermanual',
            name='tamil_manual_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
