# Generated by Django 3.1.6 on 2022-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20220117_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypewiseusermanual',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
