# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0002_farmerclustermap_userclustermap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerclustermap',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='farmerclustermap',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerclustermap',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='userclustermap',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FarmerClusterMap',
        ),
    ]
