# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_auto_20200319_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='collaborated_with_company_on',
            new_name='cultivated_for_ccgb_since',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_land_added',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_land_verified',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_land_verified_by',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_land_verified_on',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_water_added',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_water_verified',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_water_verified_by',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='all_water_verified_on',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='family_card_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_data_source_ref_id',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='invited_on',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='voter_card_epic_number',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdatasource',
            name='contact_mobile_number',
            field=models.CharField(default='1', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerdatasource',
            name='contact_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerdatasource',
            name='source_object_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
