# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0004_auto_20200319_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_code',
            new_name='code',
        ),
    ]
