# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0006_auto_20200319_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='hobli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Hobli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Village'),
            preserve_default=False,
        ),
    ]
