# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0008_farmer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
