# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-24 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0001_initial'),
        ('instance', '0010_auto_20200320_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationMethodCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTypeCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('area', models.FloatField(help_text='Area in Acre')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_calculated_via_geo_fencing', models.FloatField(blank=True, help_text='Area as per GPS', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('Irrigation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.IrrigationMethodCv')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Crop')),
                ('cultivation_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.CultivationPhase')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.District')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
                ('hobli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Hobli')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.SoilTypeCv')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.State')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Taluk')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Village')),
            ],
        ),
        migrations.CreateModel(
            name='SowingBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing')),
            ],
        ),
    ]
