# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import instance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0011_cultivationphase_irrigationmethodcv_soiltypecv_sowing_sowingboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=instance.models.get_farmer_image_save_location)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NurseryMainFieldMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SowingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(max_length=1000, upload_to=instance.models.get_sowing_image_save_location)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=instance.models.get_user_image_save_location)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('verified_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('verified_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('device_datacapture_datetime', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_resource_created_by', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='IrrigationMethodCv',
            new_name='IrrigationMethod',
        ),
        migrations.RenameModel(
            old_name='SoilTypeCv',
            new_name='SoilType',
        ),
        migrations.RenameField(
            model_name='sowing',
            old_name='Irrigation_method',
            new_name='irrigation_method',
        ),
        migrations.AddField(
            model_name='waterresource',
            name='irrigation_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.IrrigationMethod'),
        ),
        migrations.AddField(
            model_name='waterresource',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_resource_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sowingimage',
            name='sowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='sowingimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurserymainfieldmap',
            name='sowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowing_which_is_from_nursery', to='instance.Sowing'),
        ),
    ]
