# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0012_auto_20200325_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowing',
            name='water_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sowing',
            name='water_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterresource',
            name='water_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterresource',
            name='water_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterType'),
            preserve_default=False,
        ),
    ]
