# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0013_auto_20200325_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop_under_cultivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Crop'),
        ),
    ]
