# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0014_auto_20200329_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLogForCheckbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_answer_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLogForDropDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_answer_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLogForNumberInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answer_added_by', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLogForPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_answer_added_by', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLogForRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_answer_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLogForTextInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_current', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer_added_by', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ordinal', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('ordinal', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='QuestionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('create_new_answer_row_on_update', models.BooleanField(default=False)),
                ('depends_on_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_question', to='instance.Question')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instance.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionSection')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionValidationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionValidatorCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='questionvalidationconfig',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionValidatorCv'),
        ),
        migrations.AddField(
            model_name='questionconfig',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionType'),
        ),
        migrations.AddField(
            model_name='questionconfig',
            name='show_when_the_answer_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionAnswerChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionSubSection'),
        ),
        migrations.AddField(
            model_name='answerlogfortextinput',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogfortextinput',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogfortextinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogfortextinput',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionAnswerChoice'),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer'),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogforradio',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AddField(
            model_name='answerlogforpassword',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogforpassword',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogforpassword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogforpassword',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AddField(
            model_name='answerlogfornumberinput',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogfornumberinput',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogfornumberinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogfornumberinput',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionAnswerChoice'),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer'),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogfordropdown',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.QuestionAnswerChoice'),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer'),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Question'),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='sowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing'),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerlogforcheckbox',
            name='water_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterResource'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswerchoice',
            unique_together=set([('question', 'text')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('subsection', 'text')]),
        ),
    ]
