# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0015_auto_20200330_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='agreement_date',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='communication_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Language'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Gender'),
        ),
    ]
