# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0016_auto_20200331_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerClusterSeasonMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Cluster')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Farmer')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cluster_map_done_by', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
            ],
        ),
    ]
