# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0017_farmerclusterseasonmap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AfsFarmerMap',
            new_name='UserFarmerMap',
        ),
    ]
