# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0018_auto_20200407_0646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentfarmermap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='agentfarmermap',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentfarmermap',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='agentfarmermap',
            name='season',
        ),
        migrations.AlterUniqueTogether(
            name='userfarmermap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfarmermap',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='userfarmermap',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='userfarmermap',
            name='season',
        ),
        migrations.DeleteModel(
            name='AgentFarmerMap',
        ),
        migrations.DeleteModel(
            name='UserFarmerMap',
        ),
    ]
