# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_bloodgroup'),
        ('instance', '0020_auto_20200407_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.BloodGroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_licence_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
