# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0023_userprofile_emergency_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_harvest', models.DateField()),
                ('value', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('device_datacapture_datetime', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Harvest')),
            ],
        ),
        migrations.CreateModel(
            name='harvestPropertyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('display_term', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='harvestproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.harvestPropertyName'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.HarvestUnit'),
        ),
    ]
