# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0024_auto_20200519_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='business',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='sowing',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='harvestproperty',
            name='harvest',
        ),
        migrations.RemoveField(
            model_name='harvestproperty',
            name='property',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='HarvestProperty',
        ),
        migrations.DeleteModel(
            name='harvestPropertyName',
        ),
        migrations.DeleteModel(
            name='HarvestUnit',
        ),
    ]
