# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0026_auto_20200606_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='post_cheque_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
