# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0027_auto_20200614_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModuleCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsertypeBasedAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('hardware_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.HardwareDevice')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.ActionModuleCv')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.OperationCv')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.UserType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertypebasedaccesscontrol',
            unique_together=set([('user_type', 'module', 'operation', 'hardware_device')]),
        ),
    ]
