# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0028_auto_20200708_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowing',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
