# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0031_auto_20200829_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowing',
            name='is_geo_fencing_is_automatic',
            field=models.BooleanField(default=True),
        ),
    ]
