# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0033_sowingboundarymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowing',
            name='water_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.WaterType'),
        ),
    ]
