# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0034_auto_20210213_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowing',
            name='irrigation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instance.IrrigationMethod'),
        ),
    ]
