# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0035_auto_20210213_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclustermap',
            name='unique_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
