# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0036_userclustermap_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecodebank',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instance.Season'),
            preserve_default=False,
        ),
    ]
