# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0037_userprofilecodebank_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilecodebank',
            unique_together=set([('business', 'season', 'user_type', 'prefix_code')]),
        ),
    ]
