# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0038_auto_20210317_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSeasonMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Cluster')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Season')),
            ],
        ),
    ]
