# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0041_auto_20210319_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_code', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix_code', models.CharField(blank=True, max_length=10, null=True)),
                ('last_count', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Business')),
            ],
        ),
    ]
