# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0042_farmercodebank'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='land_rtc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
