# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-20 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0043_farmer_land_rtc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerclusterseasonmap',
            name='seasonal_farmer_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
