# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0045_farmerbankdetails_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingActivityImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=instance.models.get_sowing_avtivity_image_save_location)),
                ('cultivation_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.CultivationPhase')),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.Sowing')),
            ],
        ),
    ]
