# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0046_showingactivityimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='short_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
