# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-22 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0049_gapgradecv_seasonbasedgap_seasonbasesfarmergpalog_tempseasonbasedgap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonbasesfarmergpalog',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonbasesfarmergpalog',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonbasesfarmergpalog',
            name='tp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
