# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0051_farmer_is_demo_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonbasesfarmergpalog',
            name='is_skip',
            field=models.IntegerField(default=0),
        ),
    ]
