# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0052_seasonbasesfarmergpalog_is_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='is_demo_farmer',
        ),
        migrations.AlterField(
            model_name='seasonbasesfarmergpalog',
            name='is_skip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
