# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0055_remove_farmer_is_demo_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapQuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonBasedGapQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, null=True)),
                ('ordinal', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_manditory', models.BooleanField(default=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gapquestions_created_by', to=settings.AUTH_USER_MODEL)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.SeasonBasedGap')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gapquestions_modified_by', to=settings.AUTH_USER_MODEL)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.GapQuestionType')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonBasesFarmerGpaQuestionAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('farmer_gap_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.SeasonBasesFarmerGpaLog')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.SeasonBasedGapQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='TempSeasonBasedGapQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, null=True)),
                ('ordinal', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_manditory', models.BooleanField(default=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_gapquestions_created_by', to=settings.AUTH_USER_MODEL)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.TempSeasonBasedGap')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_gapquestions_modified_by', to=settings.AUTH_USER_MODEL)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.GapQuestionType')),
            ],
        ),
    ]
