# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0056_gapquestiontype_seasonbasedgapquestion_seasonbasesfarmergpaquestionanswerlog_tempseasonbasedgapquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_demo_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
