# Generated by Django 3.1.6 on 2021-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneyieldestimationtypemap',
            name='sample_percentage',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
