# Generated by Django 3.1.6 on 2021-11-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yield_calculator', '0002_cloneyieldestimationtypemap_sample_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualyield',
            name='actual_yield',
        ),
        migrations.RemoveField(
            model_name='individualyield',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plantationyield',
            name='user',
        ),
        migrations.AddField(
            model_name='plantationsample',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantationsample',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='date_of_planting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='estimated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantationyield',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
