# Generated by Django 3.1.6 on 2021-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0003_auto_20211130_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldformula',
            name='constant_ordinal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
