# Generated by Django 3.1.6 on 2021-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0004_yieldformula_constant_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualyield',
            name='estimated_yield',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='individualyield',
            name='girth',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantationsample',
            name='calculated_yield',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantationsample',
            name='girth',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantationyield',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plantationyield',
            name='estimated_yield',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='yieldformula',
            name='constant_value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
