# Generated by Django 3.1.6 on 2021-12-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0005_auto_20211201_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneyieldestimationtypemap',
            name='yield_formula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yield_calculator.yieldformulacv'),
            preserve_default=False,
        ),
    ]
