# Generated by Django 3.1.6 on 2021-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0006_cloneyieldestimationtypemap_yield_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationyield',
            name='area_in_acre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
