# Generated by Django 3.1.6 on 2021-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculator', '0007_plantationyield_area_in_acre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationyield',
            old_name='farmer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='yieldformula',
            name='constant_value',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
